---
name: fluentd-test

releases:
- {name: fluentd, version: latest}

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: fluentd
  instances: 1
  azs: [europe-west1-b]
  jobs:
  - name: fluentd
    release: fluentd
    properties:
      tls:
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIIEpDCCAowCCQDVjhyEarskAzANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAkx
          MC4wLjguMTIwHhcNMTgwODE0MDkxODUwWhcNMTkwODE0MDkxODUwWjAUMRIwEAYD
          VQQDDAkxMC4wLjguMTIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDf
          ysTUxDsS7DYHsACd1Wm7JcTW0pJTZzglmjTPsZVuzQ5kw5k5aSO6N3aCfnHxnwp3
          WuyFyz5L19Nut8QhX+P/NMyT29ZlZHy4HI3u/O9WzyXoFMjWFMxvwlFrXP7Jw/sS
          XYuN9wChxT+wT5/h4FQQWh7AnxI3l12D4C489zNrBYBJoNdzc3FPKRdeOUFMQV75
          HhRDOqQrJ37KWyZzEUEmFrWPgA0v35JYIVo0b9/B5RKSD3t1nQawnHUd3mZxxagM
          I0pjZrl7Z+kxxO5AvpCrrCYncJNYYnCvd2k48yYE+rrNcXTS6wKr7NjadrGQBbLy
          w3hRvz7yfWMlkACMhoEDAOZmV8uSLc4nIs5ZQyNzaWXU4QqYtM3WXIcEdiHepSzg
          Jhk2jafW2jvBFUbj4Az51Qj4TGQmV34hAD3SG6KxdmNiavLjec45RO4P2OpEHK15
          J6SAgFMVD/ADZjaByP+j5aCbGYudGVlo0SMIbmGIaFkHf0Tc4UQrBeQ1pkDtbyKc
          ZuOH4KwtMGLab77aP1mHjwOSA/VidELBFfCLxPmPtN63QSt2Yebw8QOA2TqlQp4J
          Sfh1AmMtyyNrkewVxNK+/vjMdIip2xiubw5yHS7p5K6+bAq4rdK0ylSNxu4Fr6ev
          whA3GM3mXkfrCkZQBmefghlE39podVhVpnNIoMpkdwIDAQABMA0GCSqGSIb3DQEB
          CwUAA4ICAQBKhNa3EQAHmIJzll8sMYkBgsLy2bv6+A9cKE+rZcKXpurScjrJFLko
          Aflif23z7ANi0dQoN8AIc8KRE5Ci2OAY7ZfwJqUatqKmdv07FD+phKo7y+eyBW4l
          CZQCPAqAK1DRJ9TOqf/HioNUVsla9H2eSuAX44tPT8xh/T1Ur7d4zNY2oqBBM9ul
          6H60Kzp161nP6USMb0lTmQ6A0LIXQkruWYo1j+JA0el7WvVC9dXcJO/6M3/SqcSG
          RUaN5d2q8rhI6ym5k2OqV2U7CSBsw0bU18hAmiGYZgQRVFT7Vd45iea1sC4xFBHw
          wlC6gv5QWWOYWz+6GAwAUvE9XGbsl70XHUiWxhodW4IzSXk+2WuEXIn8XzV2AtZy
          i7XeDDHoaSZo8+3gPFhzpMQleuJaecxy1roQSC4+IxEKK+GmXaKSmX1pQpMEbpQz
          q9dAnYits+sHZSd/UYHfe0/21opOXndC93i2UG1LB23dXO3VTz2oyHROQRiTZoH4
          XGkTjrq9/zyxR9qDjEq2Jx3JTyhmKwBrNDLgOtcmbMg2EeHVt/l/AfWJAsj2hgHl
          0hiq8xkCZRo8L2mK+G9Yj4EhM0ZmCSDSDQoSSDKfKglei7OiLEaA+qQMnV3Bs2u0
          EbXXj41ugao/abobmH8by/siJczswhSGnp4wjVVT7C/KBeFnYHPOAQ==
          -----END CERTIFICATE-----
        private_key: |
          -----BEGIN ENCRYPTED PRIVATE KEY-----
          MIIJnzBJBgkqhkiG9w0BBQ0wPDAbBgkqhkiG9w0BBQwwDgQI49VFk3sNwDkCAggA
          MB0GCWCGSAFlAwQBKgQQz75eJ5CDg6NqjwZKQBMeVASCCVAd3WX431Ke8T/VztD+
          s6621pULuZpijc1PI7xBPVuhmw6yCBy0+bWrK9vguLEm7oQ+0CWbNIe50SQllxVa
          sNH/kL4bBD2q5l1JZEwvRSnEggQFBMOnSW56udxkX2YM7hdsIEtfuWhgxxHmQWmu
          Qfsy43PRO+8EeBADPw27nLmbEZXraVISRQEoAvN/OHjn26kVt7fFG6INPhXbQhSH
          RjpghJD7DFcexuRkv/LiXoq+zxfTK2lkaYtHxNC6q8EaUyv5khoPORjpziOvz6RW
          vTFxs9gwdNxFi94atXTntXP8CfgSHdP1c2ciYolErOkY1IP4g1CVBJs7s4q0WkG+
          lwQH4SVNoSp5yNa74gdy7PwQ37cAbtEg0EiznsAmlBwFqOn2YhShAtfsjkblfTKN
          wInUWGG8IU6RtF+j+CdbpZZvjn1Vp2Ft1KLKjvphf13T+cV1GzbpjHSDAgFhL2Im
          KxMoA2zeiYmhNFi3mzhzPJwIJt51y1n1KENgzq5Qi6v2zatxt2u4L2+XQxdh72U8
          CJh3E1q7pR0xuaimcUD4eX4hsNuQXdsKLa4WIwHb4Jn4seGHDvjdMqLcW+UJr2e8
          LJItAX3uzzIMWpjjKy6t9P7FmGeVeQ54rAZIXKRpeu/ai+2A0uW5GyTKwmIHimLX
          Egh5lmBwb6G8sffXV3wv6k6/acjFXhWhDzSFZZ6xyUbrRQPlY6EJb8sw3FFI0EvX
          U2tY2hP9TflUOAepKBKvl+Ruba4AnWNWKd6WQRr0mX7hjAHNQOokYyerhPfMgvqU
          WXMYENriyYLtLp1g+91ixAHBog5U090mz8h3RD26KbpkJt+u2PqCPZ7oFSA7cEGj
          ZCGbXTXtesrP1P1upTV4rD2d3/JFaAPv3gDCSi/77GCBHx/Z/RXxrsWAo+F9/kES
          Q2+Mf1RkVxGoqt7LN3L0arfCAi8/7DSoPJtpVwQXELI6IwmGKQugkoEQLzs71cLu
          +znGy0OHYHK4kjauDEzqj6N4VW0DK07RdjgorANp1qfVowJVhPty5pPmJZQzzHTm
          PRLNt6NO7oYyf6uEyLqWOkF2et0vi9K1haOfMuJTNLtkocCHYexHFztdRF1LpBiJ
          hw++RRNeLdkl17qSaKhe1jph7/fDeVPIXwb3yNyCdurOeCGXTvQA8XSOEn5CXt/e
          AZZeOtj8dl3GKRuvFmNEwvoeBQbEKXfs7e9M2cG3gq8kjReT887agSfZRc0lvQOR
          wQVi3dxDe7oozuERaM30xFCdjMR53tIzwJOTQG4mZGpY7ZeF3bagxRNgJdLUTxXR
          XHmMa7OODo7FkrcjgSTsUGbOWrA4kLnqI9BFmlTRnekO31ZYF76+1jphpSCqmPtI
          1KaovpvyTVlFMTHeFppr1ez6nKqKGMAJ/b9SCNEhcHDUwDhJ3W88XIjg3AToScsi
          O7a+dCc/uyFtQF1Thl6XWX4EUpDAz4XKZWahlxJo/yzTanES0EFK4Ro7qYp2N2G4
          ave/ufOlZuAuO1+6wbe9kr8kpBqh62JRUtWb4qXnI7tcwNemDwtGSOhFIYVFkKD6
          Ymi5D9MF+BHczhc3a4owl/2AyvMGoGHmqkxMpIGUzoz1WXhcBIktmejbNnuNOcFT
          HWB4GmmcQz2BjeIOjGplAyciuJoz2iBqMhxbhPWwKPE9BggRK+OqfUOLo2JSnvz9
          nRkeudLg3jhnC35cpoxKrAK59XTztiqs2DrM/SYDAgbcaD7v7qUSxRC4bkmA59dp
          Vv9LbnnlQsbpMO7xfHq87ape4d+Bnp/NuQCXOfy7WLe6Imp75mFRfyg79yXnx7W6
          BZJ9a32yUfyMF8IB9ouNNyo/V/+L1lTU+qwH5XNUF5dHwVl+/2KcZhaqyuCzl+ak
          r6DhCWcKwCupH1cT+3/gl98S9ftz/c0IUNS8K8xv0PZmKYHI9d/u61TEzuOi2TUd
          mAzdi8Qu1C0nDygyTHQMz9VdkDQ+2coLBXmua7QYFTEP4c8fciR8c19wYvCZvcCz
          IErbkIctSEbbPHDuhBfq2FZnnLMUZuq9uSAq9GOB52LpJbJhgnvdSZc/T3CzvfWE
          zqtBKJk3FzVypPduM6AHjg5AKu0wks+JM6H9gnQi8m+zjR+NGyXOSTsaNPMIkIWx
          9t1h62XIvKPs5JNs8Qx3Ca/7VZZICbQDjYUWkacyjEoGsYhMlRH8ZgGp0sN6oXmO
          IxB1oNfAN11sfzikN5EhliZVWfWTJ4t9vau/SmKKL4CWOaB3kTGzIaG2+6haBO/q
          QJiXXtq1ayHHOD8rqKqrzT0BxilcDZXN9vYtmsH0Egn7WuSTZNeOxlPZp4XpF8Dt
          xllHHB7OgmhmZjXhte8RCsjC7weS63TbFClTxKd7c0vuP49puKdd03lxrPPq8tfu
          EWGV3jHeiwdT0+e+mQ6aJugBDtp46p03FehzjzvctfImFhvxCNQoSGzDqK0gIVPX
          OL1bPvJLqQCZDt/rBoLgyN8ZHwnQkBh3Kc5yfluHqyDgEkEvFHoIaiDmHN4JtSIb
          9nXb433ptuVZSjCxammMeydOxeWzGinEKVSxbHZhYMj4oewijvf3SbIaWaS6iCOR
          xOSU2PSQgHcyPcFnWbbh+vn3cU2zEqXZSqiTcBMY0Jp7KG3s5ItULHa6mc43NqJ/
          V8K/n6aD98yk4YCjgdqqgla+CTshbCffCWbmie31ga+2sfscAYN6Ns567f+ERzmP
          +4UBp//cJLnIa9C8ju937KNMnR7ogHlYpyu3G6rtNQ/duBd7n6kEofGNEre5Sobc
          UAI/O94UyIbcxBlO+mtqpZGciDr1MMmMn3KLz0jS95Y27ClDkpKkjqy+XHA+lspV
          G2jsIOapXJONdZgzepUDJf17zLUfGS1LUSYF2K65I+s9giYlbFhmKJu2pM8tWpmq
          PhVNSE+6IdPictW7G9diMcJXmtAxD9ZUhWIYqUkHy/mGFN4TxGqV13+hn4VEbsV2
          8AS9UXP6ATMCrfyrcnc/bnEXu96fsloBzWe/8GReE4RzUjYCh3dAxbZvwVjwwPPU
          UeNzCNVirIfva9ExNb5heY/E1MNNy/oYZJhbuEpQjPoV8F/hEuHZI09jdIOg5QgJ
          88uvhNn3oEzhKoUZUUpZEWAL6Ur1Fsxk1/livZxTC9sF9PqDQXKHRyGW9GYYKQ5R
          qLls+vXLY5T3vZFqvrMF+UoaAg==
          -----END ENCRYPTED PRIVATE KEY-----
      bosh_dns_name: fluentd.pks.internal
      config: |
        <system>
          log_level info
        </system>

        <source>
          @type forward
          port 24224
          bind 0.0.0.0
          <transport tls>
            cert_path /var/vcap/jobs/fluentd/certs/tls_certificate
            private_key_path /var/vcap/jobs/fluentd/certs/tls_private_key
            private_key_passphrase 123abc
          </transport>
            <security>
              self_hostname 10.0.8.12
              shared_key secret
            </security>
        </source>

        <source>
          @type http
          port 8888
          bind 0.0.0.0
        </source>

        <match pks-api cfcr-agent>
          @type exec_filter
          command /var/vcap/packages/ruby/bin/ruby /tmp/enveloper.rb
          @label @stdout
          tag enveloped
          <format>
            @type json
          </format>
          <parse>
            @type json
          </parse>

          <buffer>
            @type file
            path /tmp/fluentd_enveloper.buffer
            flush_mode immediate
            chunk_limit_records 1
          </buffer>
        </match>

        <label @stdout>
          <match **>
            @type exec
            command /var/vcap/packages/ruby/bin/ruby /tmp/sender.rb
            <format>
              @type json
            </format>
            <buffer>
              @type file
              path /tmp/fluentd_sender.buffer
              flush_mode immediate
              chunk_limit_records 1
            </buffer>
          </match>
        </label>

        <match **>
          @type stdout
        </match>
  vm_type: micro
  vm_extensions:
  - public_ip
  stemcell: default
  networks:
  - name: hughson-services-subnet

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000
