---
name: fluentd-test

releases:
- {name: fluentd, version: latest}

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: fluentd
  instances: 1
  azs: [europe-west1-b]
  jobs:
  - name: fluentd
    release: fluentd
    properties:
      bosh_dns_name: fluentd.pks.internal
      config: |
        <system>
          log_level info
        </system>

        <source>
          @type forward
          port 24224
          bind 0.0.0.0
        </source>

        <match **>
          @type exec_filter
          command /var/vcap/packages/ruby/bin/ruby /tmp/enveloper.rb
          @label @stdout
          tag enveloped
          <format>
            @type json
          </format>
          <parse>
            @type json
          </parse>
          <buffer>
            @type file
            path /tmp/fluently.buffer
            flush_interval 10s
          </buffer>
        </match>

        <label @stdout>
          <match enveloped>
            @type stdout
          </match>
        </label>
  vm_type: micro
  stemcell: default
  networks:
  - name: hughson-services-subnet

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000
